# Generated by Django 3.1 on 2022-12-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sub', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2050)),
                ('video_uri', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=150)),
                ('slideimages', models.ManyToManyField(related_name='slideimage', to='Learning.Image')),
                ('splashImg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splashimg', to='Learning.image')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learning.sport')),
                ('sub_title', models.ManyToManyField(to='Learning.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='details',
            field=models.ManyToManyField(to='Learning.Topic'),
        ),
    ]
