# Generated by Django 3.1 on 2022-12-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='slideimages',
        ),
        migrations.AddField(
            model_name='sport',
            name='slide_images',
            field=models.ManyToManyField(related_name='slide_image', to='Learning.Image'),
        ),
    ]
